FROM alpine AS builder
RUN apk add --no-cache gcc musl-dev upx
COPY main.c .
RUN gcc -static -Os -fno-stack-protector -fomit-frame-pointer \
    -fno-unwind-tables -fno-asynchronous-unwind-tables \
    -Wl,--gc-sections -Wl,-z,norelro \
    -o counter main.c && \
    strip --strip-all counter && \
    upx --best --ultra-brute counter

FROM scratch
COPY --from=builder /counter /counter
CMD ["/counter"]